### ISSUE TITLE
Distribution specific build

### ISSUE THREAD

**Issue by k2t0f12d** [omega-gg/Sky#4]
The build system, and in particular the tools for fetching 3rd party prerequisites employ tools that are specific to a particular distribution. I cannot find the name and version of compatible distribution(s) in the documentation, or the distribution used by the developers for testing. This must be considered a requirement, because the build system will fail catastrophically when used anywhere else.

**Comment by 3unjee** [comment]
Hey there k2t0f12d,

The `3rdparty.sh` script currently supports Ubuntu 16.04+. And you're right, we should be more explicit about it.

**Comment by 3unjee** [comment]
3rdparty: Update the 'ubuntu' platform: https://github.com/omega-gg/Sky/commit/b6a36d759d15978fed889c8c5c3531e237a69f17.
