### ISSUE TITLE
Gentoo build failure

### ISSUE THREAD

**Issue by k2t0f12d** [omega-gg/Sky#5]
I have attempted to provide the build with versions of the prerequisite software documented, but the build fails anyway at the linking stage.

make[1]: Entering directory '/home/k2t0f12d/dev/Sky/build/qt4/src/SkCore'
rm -f libSkCore.so
g++ -m32 -Wl,-O1 -shared -o libSkCore.so Sk_p.o WController.o WControllerApplication.o WControllerDeclarative.o WControllerPlugin.o WControllerFile.o WControllerXml.o WControllerScript.o WControllerNetwork.o WControllerDownload.o WCoreApplication.o WCrypter.o WListId.o WAbstractLoader.o WLoaderNetwork.o WLocalObject.o WFileWatcher.o WCache.o WAbstractThreadAction.o WAbstractThreadReply.o WThreadActions.o WCookieJar.o WDeclarativeCoreApplication.o WScript.o WPlugin.o qtlocalpeer.o qtsinglecoreapplication.o qtsingleapplication.o moc_WController.o moc_WControllerApplication.o moc_WControllerDeclarative.o moc_WControllerPlugin.o moc_WControllerFile.o moc_WControllerXml.o moc_WControllerScript.o moc_WControllerNetwork.o moc_WControllerDownload.o moc_WCoreApplication.o moc_WAbstractLoader.o moc_WLoaderNetwork.o moc_WLocalObject.o moc_WFileWatcher.o moc_WCache.o moc_WAbstractThreadAction.o moc_WAbstractThreadReply.o moc_WThreadActions.o moc_WCookieJar.o moc_WDeclarativeCoreApplication.o moc_WScript.o moc_WPlugin.o moc_qtlocalpeer.o moc_qtsinglecoreapplication.o moc_qtsingleapplication.o   -L/usr/lib64/qt4 -lQtDeclarative -L/usr/lib64/qt4 -lQtSvg -lQtSql -lQtScript -lQtXmlPatterns -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread  
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtDeclarative.so when searching for -lQtDeclarative
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtDeclarative.so when searching for -lQtDeclarative
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtDeclarative
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtSvg.so when searching for -lQtSvg
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtSvg.so when searching for -lQtSvg
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtSvg
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtSql.so when searching for -lQtSql
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtSql.so when searching for -lQtSql
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtSql
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtScript.so when searching for -lQtScript
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtScript.so when searching for -lQtScript
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtScript
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtXmlPatterns.so when searching for -lQtXmlPatterns
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtXmlPatterns.so when searching for -lQtXmlPatterns
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtXmlPatterns
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtXml.so when searching for -lQtXml
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtXml.so when searching for -lQtXml
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtXml
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtGui.so when searching for -lQtGui
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtGui.so when searching for -lQtGui
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtGui
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtNetwork.so when searching for -lQtNetwork
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtNetwork.so when searching for -lQtNetwork
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtNetwork
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtCore.so when searching for -lQtCore
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/qt4/libQtCore.so when searching for -lQtCore
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lQtCore
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:220: ../../../../lib/libSkCore.so] Error 1
make[1]: Leaving directory '/home/k2t0f12d/dev/Sky/build/qt4/src/SkCore'
make: *** [Makefile:45: sub-src-SkCore-make_default] Error 2

**Comment by 3unjee** [comment]
> skipping incompatible /usr/lib64/qt4/libQtCore.so when searching for -lQtCore

Looks like the Qt library you're linking with has the wrong architecture.

**Comment by k2t0f12d** [comment]
When build.sh is run on my machine it fails to detect architecture, because, the check for this is simply the existence of a directory <code>/lib/x86_64-linux-gnu</code>, which is distribution specific. Other than the strong implication that 64bit binaries might reside therein, it does not reliably or robustly assure correct identification of the native word size. [Edit: also, doesn't exist on every distribution, and certainly not Gentoo]

A better way would be <code>uname -m</code>, which would show the architecture on which the kernel believes it is running.

An excellent way would be to run this:
```bash
$ gcc -xc - -include stdio.h << '...'
int main(){
#if __x86_64__
printf("64");
#else
printf("32");
#endif
}
...
$ ./a.out && rm a.out
```

**Comment by k2t0f12d** [comment]
Tested the <code>uname -m</code> solution, and it works.

I replaced:
```
 if [ -d "$lib64" ]; then
```
with:
```
    if [ $(uname -m) == "x86_64" ]; then
```

**Comment by 3unjee** [comment]
Fixed, thanks !

Scripts: Update the 64 bit check: https://github.com/omega-gg/Sky/commit/0c0b6171107df46418a898fcc7f7b2a2abf97dd8
